const ROLES = {
    EXTRAMILE_SUPERADMIN: "EXTRAMILE_SUPERADMIN",
    ORG_SUPER_ADMIN: "ORG_SUPER_ADMIN",
    ORG_ADMIN: "ORG_ADMIN",
    EMPLOYEE: "EMPLOYEE",
    USER:"USER"
}
export default ROLES;

export const OrgRoles = ["ORG_SUPER_ADMIN", "ORG_ADMIN", "EMPLOYEE"];