export const USER_GET_ALL_REQUEST = "USER_GET_ALL_REQUEST";
export const USER_GET_ALL_SUCCESS = "USER_GET_ALL_SUCCESS";
export const USER_GET_ALL_FAIL = "USER_GET_ALL_FAIL";

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_FORGOT_PASSWORD_REQUEST = "USER_FORGOT_PASSWORD_REQUEST";
export const USER_FORGOT_PASSWORD_SUCCESS = "USER_FORGOT_PASSWORD_SUCCESS";
export const USER_FORGOT_PASSWORD_FAIL = "USER_FORGOT_PASSWORD_FAIL";

export const USER_CHANGE_PASSWORD_REQUEST = "USER_CHANGE_PASSWORD_REQUEST";
export const USER_CHANGE_PASSWORD_SUCCESS = "USER_CHANGE_PASSWORD_SUCCESS";
export const USER_CHANGE_PASSWORD_FAIL = "USER_CHANGE_PASSWORD_FAIL";

export const USER_GET_USER_REQUEST = "USER_GET_USER_REQUEST";
export const USER_GET_USER_SUCCESS = "USER_GET_USER_SUCCESS";
export const USER_GET_USER_FAIL = "USER_GET_USER_FAIL";

export const USER_GET_FAV_GAMES_REQUEST = "USER_GET_FAV_GAMES_REQUEST";
export const USER_GET_FAV_GAMES_SUCCESS = "USER_GET_FAV_GAMES_SUCCESS";
export const USER_GET_FAV_GAMES_FAIL = "USER_GET_FAV_GAMES_FAIL";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";

export const USER_SEND_OTP_REQUEST = "USER_SEND_OTP_REQUEST";
export const USER_SEND_OTP_SUCCESS = "USER_SEND_OTP_SUCCESS";
export const USER_SEND_OTP_FAIL = "USER_SEND_OTP_FAIL";

export const USER_VERIFY_OTP_REQUEST = "USER_VERIFY_OTP_REQUEST";
export const USER_VERIFY_OTP_SUCCESS = "USER_VERIFY_OTP_SUCCESS";
export const USER_VERIFY_OTP_FAIL = "USER_VERIFY_OTP_FAIL";

export const USER_DELETE_BULK_REQUEST = "USER_DELETE_BULK_REQUEST";
export const USER_DELETE_BULK_SUCCESS = "USER_DELETE_BULK_SUCCESS";
export const USER_DELETE_BULK_FAIL = "USER_DELETE_BULK_FAIL";

export const DOWNLOAD_ORGANISATION_USERS_REQUEST = "DOWNLOAD_ORGANISATION_USERS_REQUEST";
export const DOWNLOAD_ORGANISATION_USERS_SUCCESS = "DOWNLOAD_ORGANISATION_USERS_SUCCESS";
export const DOWNLOAD_ORGANISATION_USERS_FAIL = "DOWNLOAD_ORGANISATION_USERS_FAIL";
